### ISSUE TITLE
TypeError: Chatbot.__init__() got an unexpected keyword argument 'likeable'

### ISSUE THREAD

**Issue by zono50** [Shreyas9400/SearXNG-WebSearch-AI#1]
2024-10-20 07:08:19,455 - INFO - Use pytorch device_name: cuda
2024-10-20 07:08:19,455 - INFO - Load pretrained SentenceTransformer: all-MiniLM-L6-v2
Traceback (most recent call last):
  File "/mnt/Kodi_Backup/Applications/SearXNG-WebSearch-AI/app.py", line 897, in <module>
    chatbot=gr.Chatbot(
  File "/home/zono50/.conda/envs/WebSearch-AI/lib/python3.10/site-packages/gradio/component_meta.py", line 179, in wrapper
    return fn(self, **kwargs)
TypeError: Chatbot.__init__() got an unexpected keyword argument 'likeable'

I keep getting this error, and i've tried to work around it, but the program never seems to run right. Any suggestions on a fix for this?

I created a .env file and put GROQ_API_KEY in there but to no avail

**Comment by Shreyas9400** [comment]
I have updated the Groq model, it works good now. Regarding the 'likeable' I will check on it, for now can you try removing the same its in line 897 chatbot function
